# Generated by Django 5.1.1 on 2024-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=50)),
                ('api_name', models.CharField(max_length=250)),
                ('webhook_url', models.URLField()),
            ],
        ),
    ]
