# Generated by Django 5.1.1 on 2024-09-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name': 'Telegram bot', 'verbose_name_plural': 'Telegram bots'},
        ),
        migrations.RenameField(
            model_name='telegramsettings',
            old_name='api_name',
            new_name='api_key',
        ),
    ]
