# Generated by Django 5.1.1 on 2024-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_alter_telegramsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={},
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='host',
            field=models.CharField(default='localhost', max_length=255),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='port',
            field=models.PositiveIntegerField(default=8443),
        ),
    ]
