# Generated by Django 5.1.1 on 2024-09-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_alter_telegramsettings_options_telegramsettings_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsettings',
            name='host',
        ),
        migrations.RemoveField(
            model_name='telegramsettings',
            name='port',
        ),
    ]
